
<?php if( $this->pageCount ) { ?> 
	<?php
    	$status = preg_match("/\/status\/[0-9]+/", $this->url(), $matches);
		if( count($matches) > 0 ) {
			$url = "/index/dashboard".$matches[0]."/page/";
		} else {
			$url = "/index/dashboard/page/";
		}
    ?>
    <div class="pagination_module">
        <!-- Previous page link --> 
        <?php if( isset($this->previous) ) { ?>
        	<a class="enabled" href="<?php echo $url.$this->previous; ?>">&lt; Previous</a> |
        <?php } else { ?> 
            <a class="disabled" href="#">&lt; Previous</a> |
        <?php } ?> 
        
        <!-- Numbered page links -->
        <?php foreach( $this->pagesInRange as $page ) { ?> 
            <?php if( $page != $this->current ) { ?>
                <a class="enabled" href="<?php echo $url.$page; ?>"><?php echo $page; ?></a> |
            <?php } else { ?>
            	<a class="active" href="#"><?php echo $page; ?></a> |
            <?php } ?>
        <?php } ?>
        
        <!-- Next page link --> 
        <?php if( isset($this->next) ) { ?> 
        	<a class="enabled" href="<?php echo $url.$this->next; ?>">Next &gt;</a>
        <?php } else { ?> 
        	<a class="disabled" href="#">Next &gt;</a>
        <?php } ?> 
    </div> <!-- end pagination_module div -->
<?php } ?>