<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>
<div class="form_options">[ <a href="/user/accountkey">Create New User</a> ]</div>
<table class="user_table hideClass" width="840">
    <thead>
    <tr>
        <th colspan=5 class="top-header">Users Manager</th>
    </tr>
    <tr>
        <th class="form-header">Name</th>
        <th class="form-header">BM Username</th>
        <th class="form-header">JC Username</th>
        <th class="form-header">M3 Username</th>
        <th class="form-header" width="20"></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->users as $user) { ?>
        <tr id="<?php echo $user['user_id']; ?>">
            <td><?php echo $user['name']; ?></td>
            <td><?php echo $user['bm_username']; ?></td>
            <td><?php echo $user['jc_username']; ?></td>
            <td><?php echo $user['m3_username']; ?></td>
            <td>
                <a href="/user/accountkey/id/<?php echo $user['user_id']; ?>">
                    <img title="edit the selected user's information" src="/images/icons/famfam/pencil.png" />
                </a>
            </td>
        </tr> 
    <?php } ?>
    </tbody>
</table>

