<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if( is_array($this->messages) && count($this->messages) > 0 ) { ?>
    <div id="messages">
        <ul>
            <?php foreach( $this->messages as $message ) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<script type="text/javascript">

</script>

<form enctype="multipart/form-data" method="post" action="/user/email-blast">
    <table class="user_table" style="width:auto;">
        <tr>
            <td class="form-header">Send To:</td>
            <td class="form-field">
                <input type="text" name="email" class="form-element" size="50" />
                <input type="file" name="email_list" class="form-element" size="50" />
            </td>
        </tr>
        <tr>
            <td class="form-header">Subject</td>
            <td class="form-field">
                <input type="text" name="subject" class="form-element" size="70" />
            </td>
        </tr>
        <tr>
            <td class="form-header" style="vertical-align:top;background-position:top;background-color:#CCC;">Email</td>
            <td class="form-field">
                <TEXTAREA name="content" class="form-element" cols="60" rows="20" id="content"></TEXTAREA>
            </td>
        </tr>
        <tr>
            <td colspan=2 class="form-submit"><input type="submit" name="submit" value="Send Emails" /></td>
        </tr>
    </table>
</form>