<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
	<div class="bread_crumb">	
		<ul>
			<li><a href="/dashboard">Home</a></li>
			<li><?php echo $this->title; ?></li>
		</ul>
	</div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if( is_array($this->messages) && count($this->messages) > 0 ) { ?>
	<div id="messages">
		<ul>
		<?php foreach( $this->messages as $message ) { ?>
			<li><?php echo $message; ?></li>
		<?php } ?>
		</ul>
	</div><!-- end messages div -->
<?php } ?>

<div class="page_description">
    <table class="special-message">
    	<tr>
            <td></td>
            <td style="text-align: center; font-size: 18px; border-bottom: 1px solid red; padding-bottom: 10px; margin-bottom: 10px; ">Password Requirements</td>
        </tr>
    	<tr>
            <td class="icon" rowspan="2"><img src="/images/warning.png" /></td>
            <td class="message">
            	- Passwords can't contain any variation of the words jarrow, password, your first name, your last name, your username or your email. <br><br>
                - Your password has to be at least 7 characters long. <br>
                - Use at least one number. <br>
                - One uppercase letter. <br>
                - One lowercase letter.<br>
                - One special symbol.<br>
                - Passwords must be changed at least once every 6 months.
            </td>
        </tr>
    </table>
</div>

<div class="container3">
    <form enctype="multipart/form-data" method="post" action="" id="profile">
        <?php echo $this->form->user_id; ?>
        <?php echo $this->form->data; ?>
        <?php echo $this->form->height; ?>
        <?php echo $this->form->width; ?>
        
        <table id="form">
            
            <tr>
                <td colspan=2 class="top-header">User Profile Manager</td>
            </tr>
            <tr>
                <td class="profile-form-header">Full Name <span style="color:#900;">(*)</span></td>
                <td class="profile-form-field"><?php echo $this->form->name; ?></td>
            </tr>
            <tr>
                <td class="profile-form-header">Email Address <span style="color:#900;">(*)</span></td>
                <td class="profile-form-field"><?php echo $this->form->email; ?></td>
            </tr>
            <tr>
                <td class="profile-form-header_2" colspan="2">
                    Please enter your current password once in order to update your profile settings.<br />
                    Please enter a new password twice in order to update your password.<br />
                </td>
            </tr>
            <tr>
                <td class="profile-form-header">Password <span style="color:#900;">(*)</span></td>
                <td class="profile-form-field"><?php echo $this->form->password_1; ?></td>
            </tr>
            <tr>
                <td class="profile-form-header">New Password<br /></td>
                <td class="profile-form-field"><?php echo $this->form->password_2; ?></td>
            </tr>
            <tr>
                <td class="profile-form-header">Confirm New Password</td>
                <td class="profile-form-field"><?php echo $this->form->password_3; ?></td>
            </tr>
            <?php if( isset($this->form->default_task) && (is_array($this->statuses) && count($this->statuses) > 0) ) { ?>
                <tr>
                    <td class="profile-form-header">Default Task</td>
                    <td class="profile-form-field"><?php echo $this->form->default_task; ?></td>
                </tr>
            <?php } ?>
            <tr>
                <td class="profile-form-header" colspan="2">Signature (upload file or sign below)</td>
            </tr>
            <tr>
                <td class="profile-form-field" colspan="2">
                    <?php echo $this->form->signature_file; ?>
                    <br /><br />

                    <div id="signature-space" style="position:relative;width:400px;height:75px;display:block;margin:auto;border:1px solid #666;"></div>
                    <br />
                    <div id="preview-space">
                        <?php if( trim($this->user->getSignature_file()) != "" ) { ?>
                            <img src="/uploads/orders/signatures/<?php echo $this->user->getSignature_file(); ?>" alt="signature" />
                        <?php } ?>
                    </div>

                    <div class="signature_links">
                        [ <a href="/user/preview/" id="preview">preview</a> ][ <a href="#" id="clear">clear</a> ]
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan=2 class="form-submit"><?php echo $this->form->submit; ?></td>
            </tr>
        </table>
    </form>
</div>