<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
	<div class="bread_crumb">	
		<ul>
			<li><a href="/dashboard">Home</a></li>
            <li><a href="/user/users">Users List</a></li>
			<li><?php echo $this->title; ?></li>
		</ul>
	</div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if( is_array($this->messages) && count($this->messages) > 0 ) { ?>
	<div id="messages">
		<ul>
		<?php foreach( $this->messages as $message ) { ?>
			<li><?php echo $message; ?></li>
		<?php } ?>
		</ul>
	</div><!-- end messages div -->
<?php } ?>

<div class="content_header"><?php echo $this->title; ?> [ user: <?php echo $this->user->getName(); ?> ]</div>
<div class="content_header" style="text-align: center;">
    <input type="hidden" id="copy_to" name="copy_to" value="<?php echo $this->user->getUser_id(); ?>"/>
    Copy From:
    <select id="user_to_copy" name="user_copy">
        <option value="">- Select User -</option>
        <?php foreach($this->user_list as $user){?>
        <option value="<?php echo  $user['user_id'];?>"><?php echo  $user['name'];?></option>
        <?php }?>
    </select>
    <button id="copy_user_groups" name="button_copy">Submit</button>
</div>
<div id="usergroup_assignments">

	<div class="not_in">
    	<table class="inner_page_table">
        	<thead>
            	<tr>
                	<td>Unassigned Groups</td>
                </tr>
            <tbody>
            	<tr>
                	<td>
                    	<div class="user_list">
                            <table class="user_page_table">
				<?php 
                                $i = 0; 
                                if(Utility_Functions::canUserAccess("readOnly")) $read_only = true;
                                else $read_only = false;
                                ?>
                                <?php foreach( $this->permission_groups as $group ) { ?>
                                    <?php if( !isset($this->user_groups[$group['permission_group_id']]['name']) ) { ?>
                                        <tr class="show" id="out_row_<?php echo $group['permission_group_id']; ?>">
                                            <td><?php echo $group['permission_group_title']; ?></td>
                                            <td class="inner-table-option" width="20">
                                            	<?php if( !$read_only ) { ?>
                                                    <a class="add" id="<?php echo $group['permission_group_id']; ?>" 
                                                        href="/page/usergroupuserassignment/group/<?php echo $group['permission_group_id']; ?>/user/<?php echo $this->user->getUser_id(); ?>">
                                                        <img src="/images/icons/famfam/add.png" title="add this user to the selected group" />
                                                    </a>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                        <?php ++$i; ?>
                                    <?php } else { ?>
                                    	<tr class="hide" id="out_row_<?php echo $group['permission_group_id']; ?>">
                                            <td><?php echo $group['permission_group_title']; ?></td>
                                            <td class="inner-table-option" width="20">
                                            	<?php if( !$read_only ) { ?>
                                                    <a class="add" id="<?php echo $group['permission_group_id']; ?>" 
                                                        href="/page/usergroupuserassignment/group/<?php echo $group['permission_group_id']; ?>/user/<?php echo $this->user->getUser_id(); ?>">
                                                        <img src="/images/icons/famfam/add.png" title="add this user to the selected group" />
                                                    </a>
                                                <?php } ?>
                                            </td>
                                        </tr>
                                    <?php } ?>
                                <?php } ?>
                            </table><!-- end page_table -->
                        </div><!-- end user_list div -->
                	</td>
                </tr>
            </tbody>
        </table><!-- end inner_page_table -->
    </div><!-- end not_in div -->
    
    <div class="is_in">
    	<table class="inner_page_table">
        	<thead>
            	<tr>
                	<td>Assigned Groups</td>
                </tr>
            </thead>
            <tbody>
            	<tr>
                	<td>
                    	<div class="user_list">
                        	<table class="user_page_table">
								<?php $i = 0; ?>
                                <?php foreach( $this->permission_groups as $group ) { ?>
                                    <?php if( isset($this->user_groups[$group['permission_group_id']]['name']) ) { ?>
                                        <tr class="show" id="in_row_<?php echo $group['permission_group_id']; ?>">
                                            <td class="inner-table-option" width="20">
                                            	<?php if( !$read_only ) { ?>
                                                    <a class="remove" id="<?php echo $group['permission_group_id']; ?>" 
                                                        href="/page/usergroupuserremoval/group/<?php echo $group['permission_group_id']; ?>/user/<?php echo $this->user->getUser_id(); ?>">
                                                        <img src="/images/icons/famfam/delete.png" title="add this user to the selected group" />
                                                    </a>
                                                <?php } ?>
                                            </td>
                                            <td><?php echo $group['permission_group_title']; ?></td>
                                        </tr>
                                        <?php ++$i; ?>
                                    <?php } else { ?>
                                    	<tr class="hide" id="in_row_<?php echo $group['permission_group_id']; ?>">
                                            <td class="inner-table-option" width="20">
                                            	<?php if( !$read_only ) { ?>
                                                    <a class="remove" id="<?php echo $group['permission_group_id']; ?>" 
                                                        href="/page/usergroupuserremoval/group/<?php echo $group['permission_group_id']; ?>/user/<?php echo $this->user->getUser_id(); ?>">
                                                        <img src="/images/icons/famfam/delete.png" title="add this user to the selected group" />
                                                    </a>
                                                <?php } ?>
                                            </td>
                                            <td><?php echo $group['permission_group_title']; ?></td>
                                        </tr>
                                    <?php } ?>
                                <?php } ?>
                			</table><!-- end user_page_table -->
            			</div><!-- end user_list div -->
            		</td>
            	</tr>
            </tbody>
        </table><!-- end inner_page_table -->
    </div><!-- end is_in div -->
    <div class="clear"></div>

</div><!-- end usergroup_assignments div -->