<style>
    #scrolling{
        width: 40%;
        border: 1px solid black;
        position: fixed;
        left: 50%;
        margin-left: -20%;
        /* height: 40px; */
        background-color: white;
        padding: 5px;
        display:  none;
        z-index: 9;
    }
    .site_content{
        padding-bottom: 800px !important;
    }
    #scan_activation{
        font-size: 14px; 
        font-weight: bold; 
        float: left; 
        padding: 7px; 
        border-radius: 10px; 
        margin-left: 20px; 
        color:white;
        cursor: pointer;
    }
    .higlight_row{
        color: black;
        background-color: yellow;
    }
    .code_data{
        width: 100px;
        overflow: hidden;
    }
</style>
<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>
<?php
$cust_id = $this->invoice_data['header']['cust_id'];
$curr_inv_id = ($this->invoice_data['header']['inv_id'])?$this->invoice_data['header']['inv_id']:0;
$cust_name = ($this->customers[$cust_id]['cust_name'])?$this->customers[$cust_id]['cust_name']:'';
?>
<div class="form_options">
    [ <a href="/wholesale/invoices">Paid Invoices</a> ]
    [ <a href="/wholesale/pending-invoices">Pending Invoices</a> ]
    [ <a href="/wholesale/invoice">Start New Invoice</a> ]
    <?php if($curr_inv_id){ ?>
    <?php if($this->invoice_data['header']['inv_paid'] == 0){?>
        [ <a href="/wholesale/payment/invid/<?=$curr_inv_id?>/src/jq" id="assign_payment">
            <img width="25" title="Add payment" src="/images/icons/payment.png" />
        </a> ]
    <?php } ?>
    [ <a onclick="window.open('/wholesale/invoiceinfo/id/<?=$curr_inv_id?>/act/invoiceso','PrintRequest','width=1000,height=800')" href="javascript:;"><img width="25" title="Print Sales Order" src="/images/icons/invoice.png" /></a> ]
    [ <a onclick="window.open('/wholesale/invoiceinfo/id/<?=$curr_inv_id?>/act/print','PrintRequest','width=1000,height=800')" href="javascript:;"><img width="25" title="Print Invoice" src="/images/icons/famfam/printer.png" /></a> ]
    [ <a target="_blank" href="/wholesale/invoiceinfo/id/<?=$curr_inv_id?>/act/download"><img width="25" title="Download Invoice" src="/images/icons/famfam/disk.png" /></a> ]
    [ <a href="/wholesale/invoiceinfo/id/<?=$curr_inv_id?>/act/email"><img width="25" title="Email Invoice" src="/images/icons/famfam/email.png" /></a> ]
    <?php } ?>
</div>

<table id="form" width="720">
    <tr>
        <td colspan=2 class="top-header">Invoice Data</td>
    </tr>
    <tr>
        <td class="form-header">Search Customer</td>
        <td class="form-field">
                <select name="search_by" id="cust_search_by" style="float:right; padding: 3px;">
                    <option value="">- Search By -</option>
                    <option value="store_name"> Store Name</option>
                    <option value="address">Address</option>
                    <option value="contact">Contact</option>
                </select>
            <div class="frmSearch" style="width:405px;">
                <input autocomplete="off" type="text" class="search-box" id="search-box_cust" value="<?=$cust_name?>"  style="width:400px;"/>
                <div class="suggesstion-box" id="suggesstion-box_cust"></div>
            </div>
        </td>
    </tr>
</table>
<div id="cust_info" style="margin: 0 auto;">
</div>
    <form method="post" action="" class="show-loader form_submit">
    <input name="cust_id_inv" id="cust_id_inv" value="<?= $this->invoice_data['header']['cust_id'] ?>" type="hidden"/>
    <input name="curr_inv_id" id="curr_inv_id" value="<?= $curr_inv_id ?>" type="hidden"/>
    
    <div id="scrolling" >
        <div id="total_lines_qtys" style="float: left; border: 1px solid black; width: 40px; height: 25px; margin-right: 10px; font-size: 16px; font-weight: bold; padding-top: 5px;"></div>
        <input type="submit" name="submit" value="Save" style="padding:7px; float: left"/>
        
        <p id="scan_activation" style=""></p>
        <input name="scan_product" id="scan_product" style="border-radius: 5px; padding: 5px; border: 2px solid lightblue;"/>
        
        <img src="/images/icons/misc/gtk-add.png" class="add_item" title="Add New Line" alt="add item" style="cursor: pointer; float: right; width: 30px; border: 1px solid black;">
    </div>
    
    <div id="products" style="display: none; margin-top: 40px;">
        <table id="form" width="900" class="product_table">
            <thead>               
                <tr>
                    <td colspan=11 class="top-header">
                        Add Items
             <?php if($curr_inv_id){ ?>
                        <p style="float:right;">Inv No <?=$curr_inv_id?></p>
             <?php } ?>
                    </td>
                </tr>
                <tr>
                    <td class="form-header"></td>
                    <td class="form-header"><input type="checkbox" id="check_all" /></td>
                    <td class="form-header" width='300'>Desc</td>
                    <td class="form-header">Code</td>
                    <td class="form-header">Avl Qty</td>
                    <td class="form-header">Line Type</td>
                    <td class="form-header">Qty</td>
                    <td class="form-header">Price</td>
                    <td class="form-header">Last PP</td>
                    <td class="form-header">Line Total</td>
                    <td class="form-header">
                        <img src="/images/icons/famfam/add.png" class="add_item" alt="add item" style="cursor: pointer;">
                    </td>
                </tr>
            </thead>
            <tbody>
                <?php
                if ($cust_id != '' || ( is_array($this->invoice_data['header']) && array_key_exists('cust_id', $this->invoice_data['header']) ) ) {
                    $i = 0;
                    foreach ($this->invoice_data['lines'] as $line) {
                        $i++;
                        ?>
                        <tr class="prod_rows" id="prod_<?= $i ?>">
                            <td class="form-field">
                                <?= $i ?>
                                <input type="hidden" name="line_count[]" value="<?= $i ?>"/>
                            </td>
                            <td class="form-field">
                                <input type="checkbox" class="check_line_count" id="checkline_<?= $i ?>" />
                            </td>
                            <td class="form-field">
                                <?php
                                        $val_new = $this->products[$line['prod_id']]['prod_id'];
                                        $desc_new = $this->products[$line['prod_id']]['prod_desc'];
                                ?>
                                <div class="frmSearch" style="width:405px;">
                                    <input autocomplete="off"  rel='<?= $i ?>' type="text" class="search-box search-box_product" id="search-box_<?= $i ?>" value="<?= $desc_new ?>"  style="width:400px;"/>
                                    <div class="suggesstion-box" id="suggesstion-box_<?= $i ?>"></div>
                                </div>
                                <input type="hidden" class="product_saved" name="product_<?= $i ?>" value="<?= $val_new ?>"/>
                            </td>
                            <!--<td class="form-field"><input type="text" name="code_<?= $i ?>" value="<?= $line['prod_code'] ?>" size="12" /></td>-->
                            <td class="form-field"><div class="code_data product_scan" id="code_<?= $i ?>"><?= $line['prod_code'] ?></div></td>
                            <td class="form-field"><div id="desc_<?= $i ?>"><?= $line['prod_name'] ?></div></td>
                            <td class="form-field">
                                <select name="linetype_<?= $i ?>" class="inv_line_type">
                                    <option <?php echo ($line['inv_line_type'] == 1) ? 'selected="selected"' : ''; ?> value="1">Sale</option>
                                    <option <?php echo ($line['inv_line_type'] == 2) ? 'selected="selected"' : ''; ?> value="2">Return</option>
                                    <option <?php echo ($line['inv_line_type'] == 3) ? 'selected="selected"' : ''; ?> value="3">Damage</option>
                                </select>
                            </td>
                            <td class="form-field"><input type="text" autocomplete="off" name="qty_<?= $i ?>" value="<?= $line['product_qty'] ?>" class="line_qty" size="5" maxlength="4" required="required"/></td>
                            <td class="form-field"><input type="text" autocomplete="off" name="price_<?= $i ?>" value="<?= $line['product_price'] ?>" class="line_price" maxlength="6" size="5" required="required"/></td>
                            <td class="form-field">
                                <div id="line_Last_<?= $i ?>"><?= $line['inv_last_pp'] ?></div>
                                <input type="hidden" name="line_Last_input_<?= $i ?>" value="<?= $line['inv_last_pp'] ?>" />
                            </td>
                            <td class="form-field"><div id="line_total_<?= $i ?>"><?= $line['product_qty'] * $line['product_price'] ?></div></td>
                            <td class="form-field">
                                <a class="delete_supplement" rel="del_<?= $i ?>">
                                    <img src="/images/icons/famfam/delete.png" title="delete selected item">
                                </a>
                            </td>
                        </tr>
                        <?php
                    }
                }
                ?>
            </tbody>
        </table>
        <table id="form" width="700">
             <?php if($curr_inv_id){ ?>
                <tr>
                    <td colspan=2 class="top-header" style="text-align: center;">Inv No <?=$curr_inv_id?></td>
                </tr>
             <?php } ?>
            <tr> 
                <td style="text-align:right;">
                    <b>Invoice Sub Total &nbsp;<div style="display:inline-block; width: 70px;" id="invoice_sub_total"></div></b>
                    <input type="hidden" name="invoice_sub_total_input" id="invoice_sub_total_input"/>
                </td>
                <td>
                    <b>Total Qty &nbsp;&nbsp; <div style="display:inline-block; width: 100px;" id="invoice_qty_total"></div></b>
                    <input type="hidden" name="invoice_qty_input" id="invoice_qty_input"/>
                    &nbsp;&nbsp;<b>Credits &nbsp;&nbsp; <div style="display:inline-block; width: 100px;" id="invoice_credit_div"></div></b>
                    <input type="hidden" name="invoice_credit_input" id="invoice_credit_input"/>
                </td>
            </tr>
            <tr>
                <td style="text-align:right;"><b>Discount</b></td>
                <td><input type="number" name="discount" value="<?= $this->invoice_data['header']['inv_discount'] ?>" step="any" id="invoice_discount" size="4"/></td>
            </tr>
            
            
            <tr>
                <td style="text-align:right;">
                    <b>Shipping Charges</b>                    
                </td>
                <td>
                    <input type="number" name="inv_shipping" value="<?= $this->invoice_data['header']['inv_shipping'] ?>" step="any" maxlength="2" id="invoice_shipping" style="width:100px;"/>
                </td>
            </tr>
            
            
            <tr>
                <td style="text-align:right;">
                    <b>Paid Amount</b>                    
                </td>
                <td>
                    <input type="number" name="inv_payments" value="<?= $this->invoice_data['header']['inv_payments'] ?>" step="any" maxlength="2" id="invoice_payments" style="width:100px;"/>
                </td>
            </tr>
            
            <tr>
                <td style="text-align:right;">
                    <b>Additional Charges</b>                    
                </td>
                <td>
                    <input type="number" name="inv_outstanding" value="<?= $this->invoice_data['header']['inv_outstanding'] ?>" step="any" maxlength="2" id="invoice_outstanding" style="width:100px;"/>
                </td>
            </tr>
            
            
            
            
            <tr>
                <td style="text-align:right;">
                    <b>CC Charges %</b>
                    <input type="number" name="inv_ccp" value="<?= $this->invoice_data['header']['inv_ccp'] ?>" step="any" maxlength="2" id="invoice_ccp" style="width:40px;"/>
                </td>
                <td>
                    <b>$<input type="text" name="inv_cca" id="inv_cca_input"/>
                </td>
            </tr>
            <tr>
                <td style="text-align:right;"><b>Invoice Total</b></td>
                <td><b>$<div style="display:inline-block;" id="invoice_total"></div></b></td>
                <input type="hidden" name="invoice_total_input" id="invoice_total_input"/>
            </tr>
            <tr>
                <td style="text-align:right;"><b>Invoice Date</b></td>
                <td>
                    <input  
                    <input  
                        required="required"
                        autocomplete="off"
                        type="text" 
                        name="start_date" 
                        id="invoice_date" 
                        style="padding: 2px; background:none; color: inherit; font-size: 13px;"
                        value="<?php echo (isset($this->invoice_data['header']['inv_date']))?date('m/d/Y', strtotime($this->invoice_data['header']['inv_date'])):date('m/d/Y'); ?>"
                    />
                </td>
            </tr>
         
            <?php 
            $total_payments = 0;
            if($this->payments){ ?>
            <tr>
                <td colspan="2" style="text-align: left;font-size: 14px;">
                    <table width="100%">
                        <thead>
                            <tr>
                                <th class="top-header" colspan="8">Payments</th>
                            </tr>
                            <tr>
                                <th class="form-header"></th>
                                <th class="form-header">PID</th>
                                <th class="form-header">Date</th>
                                <th class="form-header">Method</th>
                                <th class="form-header">Reference</th>
                                <th class="form-header">User</th>
                                <th class="form-header">Amount</th>
                                <th class="form-header"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->payments as $payment){ $total_payments += $payment['payment_amount'];?>
                            <tr>
                                <td  class="form-field" >
                                    <a onclick="return confirm('Are you sure you want to delete this Payment?')" href="/wholesale/voidpayment/id/<?=$payment['payment_id']?>/invid/<?=$payment['inv_id']?>">
                                        <img width="20" title="Delete Payment" src="/images/icons/famfam/delete.png" />
                                    </a>
                                </td>
                                <td class="form-field"><?=$payment['payment_id']?></td>
                                <td class="form-field"><?=date("m/d/Y", strtotime($payment['payment_datetime']))?></td>
                                <td class="form-field"><?=$payment['payment_type']?></td>
                                <td class="form-field"><?=$payment['payment_contact']?></td>
                                <td class="form-field"><?=$payment['name']?></td>
                                <td class="form-field">$<?=number_format($payment['payment_amount'],2)?></td>
                                <td class="form-field">
                                    <a href="/wholesale/payment/id/<?=$payment['payment_id']?>/invid/<?=$curr_inv_id?>/src/jq" id="assign_payment">
<!--                                    <a href="/wholesale/payment/id/<?=$payment['payment_id']?>">-->
                                        <img title="Edit Payment" src="/images/icons/famfam/pencil.png" />
                                    </a>
                                </td>
                            </tr>
                            <?php } ?>
                            <tr>
                                <td class="form-field" colspan="6" style="text-align:right;"><b>Total Payments</b></td>
                                <td class="form-field">$<?=number_format($total_payments,2)?></td>
                                <td class="form-field">                        
                                </td>
                            </tr>
                            <tr>
                                <td class="form-field" colspan="6" style="text-align:right;"><b>Remaining Balance</b></td>
                                <td class="form-field">$<?=number_format($this->invoice_data['header']['inv_total'] - $total_payments,2)?></td>
                                <td class="form-field">                        
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <?php } ?>
   <tr>
                <td style="text-align:right;"><b>Paid</b></td>
                <td>
                    <span><?php echo ($this->invoice_data['header']['inv_paid'] == 0)?'NO':'YES' ?></span>
                </td>
            </tr>
<!--        <tr>
                <td style="text-align:right;"><b>Invoice Status</b></td>
                <td>
                    <select name="inv_status">
                        <option <?php echo ($this->invoice_data['header']['inv_status'] == 0) ? 'selected="selected"' : ''; ?> value="0">Not Paid</option>
                        <option <?php echo ($this->invoice_data['header']['inv_status'] == 1) ? 'selected="selected"' : ''; ?> value="1">Partially Paid</option>
                        <option <?php echo ($this->invoice_data['header']['inv_status'] == 2) ? 'selected="selected"' : ''; ?> value="2">Fully Paid</option>
                    </select>
                </td>
            </tr>-->
            <tr>
                <td style="text-align:right;"><b>Document Type</b></td>
                <td>
                    <select name="inv_payment">
                        <option <?php echo ($this->invoice_data['header']['inv_payment'] == 'INVOICE') ? 'selected="selected"' : ''; ?> value="INVOICE">INVOICE</option>
<!--                        <option <?php echo ($this->invoice_data['header']['inv_payment'] == 'SalesOrder') ? 'selected="selected"' : ''; ?> value="SalesOrder">SalesOrder</option>-->
                    </select>
                </td>
            </tr>
            <?php if($this->invoice_data['header']['inv_paid'] == 0){?>
                <tr>
                    <td colspan="2" style="text-align: left;font-size: 14px;"><b>Notes:</b><br/>
                        <textarea cols="20" rows="3" name="notes"><?= $this->invoice_data['header']['inv_notes'] ?></textarea>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: center;">
                        <input type="submit" name="submit" value="Save" style="padding:10px"/>
                    </td>
                </tr>
            <?php }else{?>
                <tr>
                    <td colspan="2" style="text-align: center;">
                        <span style="color: green; font-weight: bold;"><b>Invoice has been paid in full and can no longer be edited.</span>
                    </td>
                </tr>
            <?php }?>
        </table>
    </div>
</form>
    
    
<script type="text/javascript"> 
$(document).ready(function (){
    $('a#assign_payment').live("click", function (e) {
        var href = $(this).attr('href');
        var wHeight = $(window).height();
        var dHeight = wHeight * 0.80;
        var $dialog = $('<div class="dialog"></div>').load(href)
        .dialog({
            title: 'Add Payment',
            autoOpen: false,
            resizable: false,
            height: dHeight,
            modal: true,
            width: 700,
            close: function(event, ui)
            {
                $(this).dialog('destroy').remove();
            }
        });
        $dialog.dialog('open');
        return false;
    });
    
    $('form#payment_form input[name=submit],form#payment_form input[name=print]').live("click", function(e) { 
        $('input[type=hidden][name=button_clicked]').val($(this).attr('name'));
    });
    
    $('form#payment_form').live("submit", function(e) { 
        e.preventDefault();
        var formData = $(this).serializeArray();
        var inv_id = $('#inv_id').val();
        var data = { formdata: JSON.stringify(formData) };
        $.ajax({
          type: 'POST',
          url: '/wholesale/submitpayment',
          data: data,
          datatype: "html"
        }).done((data) => {
           var arr = JSON.parse(data);
           if(arr["success"]){
                if(arr["file"]){
                    window.open(arr["file"],'PrintRequest','width=1000,height=800');
                }
                window.scrollTo(0, 0);
                window.location.reload(true);
           }else{
                jAlert('<p style="font-size:18px;"><b>Plase check errors below</b> <br>'+arr["msg"],'Error');
                $("#popup_content.alert").css({'width':'470px','height':'200px','overflow-y':'auto'});
                $("#popup_container").css({'max-width':'440px'});
                $(".error").css({'width':'380px'});
           }
        }).fail((err) => {
            jAlert(err,'Error');
        });
    });
    
});
</script> 