<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>
<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>
<div class="form_options">
    [ <a href="/wholesale/invoice">Create New Invoice</a> ]
</div>
<table class="variables_table" width="1000" style="margin: 0 auto; border: 1px solid lightgray;">
    <thead>
        <tr>
            <th colspan="12" class="top-header">PAID Invoices</th>
        </tr>
        <tr> 
            <th width="10" class="form-header">Inv No</th>
            <th width="" class="form-header">Name</th>
            <th width="" class="form-header">Address</th>
<!--            <th width="100" class="form-header">Email</th>-->
            <th width="" class="form-header">Invoiced By</th>
            <th width="80" class="form-header">Inv Date</th>
            <th width="" class="form-header">Total</th>
            <th width="40" class="form-header"></th>
            <th width="40" class="form-header"></th>
            <th width="40" class="form-header"></th>
            <th width="40" class="form-header"></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $row = 0;
        $accessSleev = Utility_Functions::canUserAccess("/wholesale/invoiceinfo");
        foreach ($this->entries as $entry) {    $row++;?>
            <tr class="row_<?php echo $row % 2; ?>">
                <td><?php echo $entry['inv_id']; ?></td>
                <td><?php echo $entry['cust_name']; ?></td>
                <td><?php echo $entry['cust_address'] . ',<br>' . $entry['cust_city'] . ',' . $entry['cust_state'] . ' ' . $entry['cust_zip']; ?></td>
<!--                <td><?php echo $entry['cust_email']; ?></td>-->
                <td><?php echo $entry['name']; ?></td>
                <td><?php echo date('m/d/Y h:i A', strtotime($entry['inv_date'])); ?></td>                
                <td>$<?php echo round($entry['inv_total'],2); ?></td>
                <td style="text-align: center;">
                    <?php if ($accessSleev) { ?>
                        <a onclick="return confirm('Are you sure you want to draft this invoice?')" href="/wholesale/deactivateinvoice/id/<?php echo $entry['inv_id']; ?>/location/invoices">
                            <img width="25" title="Draft Invoice" src="/images/icons/famfam/delete.png" />
                        </a>
                    <?php } ?>
                </td>
                <td style="text-align: center;">
                    <?php if ($accessSleev) { ?>
                        <a href="/wholesale/invoice/id/<?php echo $entry['inv_id']; ?>">
                            <img width="25" title="Edit Invoice" src="/images/icons/famfam/pencil.png" />
                        </a>
                    <?php } ?>
                </td>
                <td style="text-align: center;">
                    <?php if ($accessSleev) { ?>
                        <a onclick="window.open('/wholesale/invoiceinfo/id/<?=$entry['inv_id']?>/act/print','PrintRequest','width=1000,height=800')" href="javascript:;">
                            <img width="25" title="Print Invoice" src="/images/icons/famfam/printer.png" />
                        </a>
                    <?php } ?>
                </td>
                <td style="text-align: center;">
                    <?php if ($accessSleev) { ?>
                        <a href="/wholesale/invoiceinfo/id/<?php echo $entry['inv_id']; ?>/act/email">
                            <img width="25" title="Email Invoice" src="/images/icons/famfam/email.png" />
                        </a>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>