<?php
$rowcount = count($this->picklist['lines']);
if ($rowcount > 30) {
    $pages = ceil($rowcount / 30);
} else if ($rowcount == 30) {
    $pages = 1;
} else {
    $pages = ceil($rowcount / 30);
}
$y = 0;
$page = 1;
$sumweight = 0;
$sumitem = 0;
?>
<div class="pdf">
    <?php
    echo $this->partial('/wholesale/picklistheader.phtml', array(
        "orderNumber" => $this->orderNumber,
        "picklist" => $this->picklist,
        "barcode" => $this->barcode,
        "top" => 1,
        "allpages" => $pages,
        "page" => $page,
    ));
    ?>
    <table  class="picking width_100" style="font-family: sans-serif;">                        
        <tr>
            <th width="40">Qty</th>
            <th width="120">Item Number</th>
            <th width="300">Item Desc</th>
            <th width="40">Price</th>
            <th width="40">Line Total</th>
        </tr>
        <?php
        $total_units = $total_lines = $total_price = 0;
        foreach ($this->picklist['lines'] as $pick) {
            $y++;
            $total_lines++;
            $total_units += $pick['product_qty'];
            $total_price += $pick['product_price'] * $pick['product_qty'];
            ?> 
            <tr>
                <td class="cell_center"><?php echo $pick['product_qty']; ?></td>
                <td class="cell_center"><?php echo $pick['prod_no']; ?></td>
                <td class="cell_center"><?php echo $pick['prod_desc']; ?></td>
                <td class="cell_center">$<?php echo $pick['product_price']; ?></td> 
                <td class="cell_center">$<?php echo number_format(($pick['product_price'] * $pick['product_qty']), 2); ?></td> 
            </tr>  
            <?php
            if ($page == 1) {
                $records_count = 30;
            } else if ($page > 1)
                $records_count = 30;
            
            $end_picklist = (is_array($this->picklist[$orderNumber]['lines']))?end($this->picklist[$orderNumber]['lines']):[];
            if ($y == $records_count 
                    && ($pick != $end_picklist ) 
                        && $page < $pages) {
                $y = 0;
                $page++;
                ?>
            </table>
        </div>  
        <div class="pdf">
            <?php $header = $this->picklist['header']; ?>  
            <table class="width_100" style="font-family: sans-serif; margin-top: 15px;">
                <tr>
                    <td width="20%">
                        Page <?php echo $page; ?> of <?php echo $pages; ?><br>
                    </td>
                    <td width="50%" style="text-align: center; vertical-align: bottom;">
                        <b>BNY WHOLESALE</b><br>
                        Tob Lic No. 264280896<br>
                        &nbsp;&nbsp;&nbsp; Tel: 310-988-0222 &nbsp;&nbsp;&nbsp;<br>
                        18536 Roslin Ave, Torrance, CA 90504<br>
                        <font style="font-family: sans-serif; font-size: 16px; font-weight: bold;">I N V O I C E</font>
                    </td>
                    <td width="30%" class="cell_center">
                        <b>Date</b> <br>
                        <?php echo date('m/d/Y', strtotime($header['inv_date'])); ?> <br>
                        <img src="<?php echo Zend_Registry::get("root_path") . "/public/pdf/barcode_" . trim($this->orderNumber) . ".jpg"; ?>"/><br>
                        <?php echo $this->barcode; ?>
                    </td>
                </tr>
            </table>
            
            <table class="picking width_100" style="font-family: sans-serif;border: none; border-top: 1px solid black; margin: 0 auto">
                <tr>
                    <td style=" border-left: none;border-right: none;"><b>Customer ID:<?php echo $header['cust_id']; ?></b></td>
                </tr>
            </table>
            <table class="picking width_100">
                <tr>
                    <td width="45%"><b>Sold To:</b></td>
                    <td width="45%"><b>Ship To:</b></td>
                </tr>
                <tr>
                    <td width="45%">
                        <b><?php echo $header['cust_name']; ?></b><br>
                        <?php echo $header['cust_address']; ?><br>
                        <?php echo $header['cust_city'] . ',' . $header['cust_state'] . ' ' . $header['cust_zip']; ?><br>
                        Tob Lic No.:<?php echo $header['cust_lic_no']; ?>
                    </td>
                    <td width="45%">
                        <b><?php echo $header['cust_name']; ?></b><br>
                        <?php echo $header['cust_address']; ?><br>
                        <?php echo $header['cust_city'] . ',' . $header['cust_state'] . ' ' . $header['cust_zip']; ?><br>
                    </td>
                </tr>
            </table>
            <br>

            <table  class='picking width_100' style="font-family: sans-serif;">                        
                <tr>
                    <th width="40">Qty</th>
                    <th width="120">Item Number</th>
                    <th width="300">Item Desc</th>
                    <th width="40">Price</th>
                    <th width="40">Line Total</th>
                </tr>
                <?php
            }
        }
        ?>
    </table>
</div>     
<div class="pdfrow bottom width_100">
    <table class="picking width_100"  style='margin-left:0px; margin-right: 30px; top: 0px;'>
        <tr>
            
            <td width="71%" style="text-align: left;font-size: 14px;">
                <?php if ($this->picklist['header']['inv_notes'] != '') { ?>
                <b>Notes:</b><?php echo $this->picklist['header']['inv_notes']; ?> <br><br>
                <?php } ?>
                ALL CALIFORNIA CIGARETTES AND TOBACCO TAXES ARE INCLUDED IN THE TOTAL OF THE INVOICE
            </td>
            
            <td width="29%"  style="text-align: left;font-size: 16px;">
               <table class="picking width_100" style="width: 330px; height: 100%; top: 0px;">
                    <tr>
                        <td colspan="2">
                            <b>Total Lines </b> <?php echo $total_lines; ?>&nbsp;&nbsp;<b> Qty </b> <?php echo number_format($total_units); ?>
                        </td>
                    </tr>
                    
                    <?php if ((float) $this->picklist['header']['inv_credits'] > 0) { ?>
                    <tr>
                        <td>
                            <b>Invoice Credits:</b> 
                        </td>
                        <td>$<?php echo number_format($this->picklist['header']['inv_credits'], 2); ?></td>
                    </tr>
                    <?php } ?>
                    
                    <tr>
                        <td>
                            <b>Invoice Sub Total:</b> 
                        </td>
                        <td>$<?php echo number_format($total_price, 2); ?></td>
                    </tr>
                
                    <?php if ((float) $this->picklist['header']['inv_outstanding'] > 0) { ?>
                    <tr>
                        <td>
                            <b>Additional Charges:</b>
                        </td>
                        <td>$<?php echo number_format($this->picklist['header']['inv_outstanding'], 2); ?></td>
                    </tr>
                    <?php } ?>
                    
                    <?php if ((float) $this->picklist['header']['inv_shipping'] > 0) { ?>
                    <tr>
                        <td>
                            <b>Shipping Charges:</b>
                        </td>
                        <td>$<?php echo number_format($this->picklist['header']['inv_shipping'], 2); ?></td>
                    </tr>
                    <?php } ?>
                    
                    <?php if ((float) $this->picklist['header']['inv_payments'] > 0) { ?>
                    <tr>
                        <td>
                            <b>Paid:</b>
                        </td>
                        <td>$<?php echo number_format($this->picklist['header']['inv_payments'], 2); ?></td>
                    </tr>
                    <?php } ?>
                    
                    <?php if ((float) $this->picklist['header']['inv_discount'] > 0) { ?>
                    <tr>
                        <td>
                            <b>Invoice Discount:</b>
                        </td>
                        <td>$<?php echo number_format($this->picklist['header']['inv_discount'], 2); ?></td>
                    </tr>
                    <?php } ?>
                    
                    <?php if ((float) $this->picklist['header']['inv_cca'] > 0) { ?>
                    <tr>
                        <td>
                            <b>CC Charges:</b>
                        </td>
                        <td>$<?php echo number_format($this->picklist['header']['inv_cca'], 2); ?></td>
                    </tr>
                    <?php } ?>
                    

                    
                    <?php $inv_final_total = $total_price 
                                            - $this->picklist['header']['inv_discount'] 
                                            + $this->picklist['header']['inv_shipping']
                                            + $this->picklist['header']['inv_outstanding']
                                            - $this->picklist['header']['inv_payments']
                                            + $this->picklist['header']['inv_cca']
                            ; ?>
                    
                    <tr>
                        <td>
                            <b>Invoice Total:</b></b>
                        </td>
                        <td>$<?php echo number_format($inv_final_total, 2); ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
