<?php
$rowcount = count($this->picklist['lines']);
$lines_per_page = 25;
if ($rowcount > $lines_per_page) {
    $pages = ceil($rowcount / $lines_per_page);
} else if ($rowcount == $lines_per_page) {
    $pages = 1;
} else {
    $pages = ceil($rowcount / $lines_per_page);
}
$y = 0;
$page = 1;
$sumweight = 0;
$sumitem = 0;
?>
<div class="pdf">
    <?php
    echo $this->partial('/wholesale/picklistheader_1.phtml', array(
        "orderNumber" => $this->orderNumber,
        "picklist" => $this->picklist,
        "barcode" => $this->barcode,
        "top" => 1,
        "allpages" => $pages,
        "page" => $page,
    ));
    ?>
    <table  class="picking width_100" style="font-family: sans-serif;">                        
        <tr>
            <th width="40">Qty</th>
            <th width="40">Type</th>
            <th width="120">Item Number</th>
            <th width="300">Item Desc</th>
            <th width="40">Price</th>
            <th width="40">Total</th>
        </tr>
        <?php
        $total_units = $total_lines = $total_price = 0;
        foreach ($this->picklist['lines'] as $pick) {
            $y++;
            $total_lines++;
            $total_units += abs($pick['product_qty']);
            $total_price += $pick['product_price'] * $pick['product_qty'];
            ?> 
            <tr>
                <td class="cell_center"><?php echo $pick['product_qty']; ?></td>
                <td class="cell_center"><?php echo $pick['line_type']; ?></td>
                <td class="cell_center"><?php echo $pick['prod_no']; ?></td>
                <td class="cell_center"><?php echo $pick['prod_desc']; ?></td>
                <td class="cell_center">$<?php echo $pick['product_price']; ?></td> 
                <td class="cell_center">$<?php echo number_format(($pick['product_price'] * $pick['product_qty']), 2); ?></td> 
            </tr>  
            <?php
            if ($page == 1) {
                $records_count = $lines_per_page;
            } else if ($page > 1)
                $records_count = $lines_per_page;
            
            $end_picklist = (is_array($this->picklist[$orderNumber]['lines']))?end($this->picklist[$orderNumber]['lines']):[];
            if ($y == $records_count 
                    && ($pick != $end_picklist ) 
                        && $page < $pages) {
                $y = 0;
                $page++;
                ?>
            </table>
        </div>  
        <div class="pdf">
            <?php $header = $this->picklist['header']; ?>  
            <table class="width_100" style="font-family: sans-serif;">
                <tr>
                    <td width="30%" >
                        <b>Day Star Distibution</b><br>
                        Phone # 213-265-7472 <br>
                        Fax # 213-265-7473<br>
                        320 E 3RD ST, <br>LOS ANGELES, CA 90013<br>
                    </td>
                    <td width="40%" style="text-align: center;">
                        <img width="240" src="<?php echo Zend_Registry::get("full_url") . "/images/logo_home.png"; ?>"/><br>
                    </td>
                    <td width="30%" style="text-align: right;">
                        <table class="picking cell_center" cellpadding="0" cellspacing="0" style="font-family: sans-serif;">
                            <tr>
                                <td style="text-align: left; font-size: 12px;">Page <?php echo $page; ?> of <?php echo $pages; ?></td>
                                <td style="text-align: right; font-size: 22px;">Invoice</td>
                            </tr>
                            <tr>
                                <td>Date</td>
                                <td>Invoice #</td>
                            </tr>
                            <tr>
                                <td style="tex"><?php echo date('m/d/Y', strtotime($header['inv_date'])); ?> </td>
                                <td>
                                    <?php echo $this->barcode; ?><br>
                                    <img src="<?php echo Zend_Registry::get("root_path") . "/public/pdf/barcode_" . trim($this->orderNumber) . ".jpg"; ?>"/>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" style="text-align: center; font-size: 12px;padding: 5px 0px;">Tobacco Lic# 222271552</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
            <table class="picking width_100">
                <tr>
                    <td width="45%"><b>Bill To:</b></td>
                    <td width="45%"><b>Ship To:</b></td>
                </tr>
                <tr>
                    <td width="45%">
                        <b><?php echo $header['cust_name']; ?></b><br>
                        <?php echo $header['cust_address']; ?><br>
                        <?php echo $header['cust_city'] . ',' . $header['cust_state'] . ' ' . $header['cust_zip']; ?>
                    </td>
                    <td width="45%">
                        <b><?php echo $header['cust_name']; ?></b><br>
                        <?php echo $header['cust_address']; ?><br>
                        <?php echo $header['cust_city'] . ',' . $header['cust_state'] . ' ' . $header['cust_zip']; ?><br>
                    </td>
                </tr>
            </table>
            <table class="picking width_100" style=" text-align: center; font-family: sans-serif;border: none; border-top: 1px solid black; margin: 0 auto">
                <tr>
                    <td>Sellers Permit#</td>
                    <td>Tobacco Lic#</td>
                    <td>Expiration Date</td>
                    <td>Rep</td>
                    <td>E-mail</td>
                    <td>Web Site</td>
                </tr>
                <tr>
                    <td width="14%"></td>
                    <td width="13%"><?php echo $header['cust_lic_no']; ?></td>
                    <td width="15%"><?php echo (!empty(trim($header['cust_lic_exp'])) && $header['cust_lic_exp'] != '0000-00-00')?date('m/d/Y', strtotime($header['cust_lic_exp'])):''; ?></td>
                    <td width="22%"><?php echo $header['cust_contact']; ?></td>
                    <td width="26%"><?php echo $header['cust_email']; ?></td>
                    <td width="10%"></td>
                </tr>
            </table>
            <br>

            <table  class='picking width_100' style="font-family: sans-serif;">                        
                <tr>
                    <th width="40">Qty</th>
                    <th width="40">Type</th>
                    <th width="120">Item Number</th>
                    <th width="300">Item Desc</th>
                    <th width="40">Price</th>
                    <th width="40">Total</th>
                </tr>
                <?php
            }
        }
        ?>
    </table>
</div>     
<div class="pdfrow bottom width_100">
    <table class="picking width_100"  style='margin-left:0px; margin-right: 30px; top: 0px;'>
        <tr>
            <td width="71%" style="text-align: left;font-size: 14px;">
                <?php if ($this->picklist['header']['inv_notes'] != '') { ?>
                    <b>Notes:</b><?php echo $this->picklist['header']['inv_notes']; ?>
                <?php } ?>
                All California cigarette and tobacco product taxes are included in the total amount in this invoice. BATTERY WARNING:
                Do Not Carry Or Store Batteries Together Where They May Be Exposed To Metals. Always Shut Off Devices When Not In Use.
                Not For Hybrid Mods Use. If Batteries Are Improperly Used Or Stored, Day Star Distribution Inc. Will Not Be Responsible For Damage, 
                Injury, Or Death. *WARNING: Salt-Nicotine Are NOT For Sub-oHm Use. We Reserve The Right To Limit Or Refuse Any Refund Or Exchange. 
                All Return Or Exchange Are Subject To A Verification Process. 
                Invoice Will Need To Be Presented To Most Unopened And Unexpired Items In New Condition Purchased In Day Star Distribution. 
                Due to PMTA regulation, we are not accepting any return or exchange for any products until further notice.<br>
                All sales are final .. no return or exchange on any product.
            </td>
            <td width="29%"  style="text-align: left;font-size: 16px;">
                <table class="picking width_100" style="width: 330px; height: 100%; top: 0px;">
                    <tr>
                        <td colspan="2">
                            <b>Total Lines </b> <?php echo $total_lines; ?>&nbsp;&nbsp;<b> Qty </b> <?php echo number_format($total_units); ?>
                        </td>
                    </tr>
                <?php if ((float) $this->picklist['header']['inv_credits'] > 0) { ?>
                    <tr>
                        <td>
                            <b>Invoice Credits:</b> 
                        </td>
                        <td>$<?php echo number_format($this->picklist['header']['inv_credits'], 2); ?></td>
                    </tr>
                <?php } ?>
                    <tr>
                        <td>
                            <b>Invoice Sub Total:</b> 
                        </td>
                        <td>$<?php echo number_format($total_price, 2); ?></td>
                    </tr>
                
                <?php if ((float) $this->picklist['header']['inv_discount'] > 0) { ?>
                    <tr>
                        <td>
                            <b>Invoice Discount:</b>
                        </td>
                        <td>$<?php echo number_format($this->picklist['header']['inv_discount'], 2); ?></td>
                    </tr>
                    
                <?php } ?>
                <?php if ((float) $this->picklist['header']['inv_shipping'] > 0) { ?>
                    <tr>
                        <td>
                            <b>Shipping Charges:</b>
                        </td>
                        <td>$<?php echo number_format($this->picklist['header']['inv_shipping'], 2); ?></td>
                    </tr>
                <?php } ?>
                <?php if ((float) $this->picklist['header']['inv_cca'] > 0) { ?>
                    <tr>
                        <td>
                            <b>CC Charges:</b>
                        </td>
                        <td>$<?php echo number_format($this->picklist['header']['inv_cca'], 2); ?></td>
                    </tr>
                    
                <?php } ?>
                <?php $inv_final_total = $total_price - $this->picklist['header']['inv_discount'] + $this->picklist['header']['inv_shipping'] + $this->picklist['header']['inv_cca']; ?>
                    <tr>
                        <td>
                            <b>Invoice Total:</b></b>
                        </td>
                        <td>$<?php echo number_format($inv_final_total, 2); ?></td>
                    </tr>
                    
                    <tr>
                        <td>
                            <b>Total Payments:</b></b>
                        </td>
                        <td>$<?php echo number_format($this->payments, 2); ?></td>
                    </tr>
                
                    <tr>
                        <td>
                            <b>Balance Due:</b></b>
                        </td>
                        <td>$<?php echo number_format($inv_final_total - $this->payments, 2); ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
