<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>
<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>
<div class="form_options">
    [ <a href="/wholesale/payment">Add New Payment</a> ]
</div>
<table class="variables_table" width="950" style="margin: 0 auto; border: 1px solid lightgray;">
    <thead>
        <tr>
            <th colspan="11" class="top-header">Payments Manager</th>
        </tr>
        <tr> 
            <th width="10" class="form-header"></th>
            <th width="10" class="form-header">InvNo</th>
            <th width="" class="form-header">Customer</th>
            <th width="" class="form-header">Address</th>
            <th width="" class="form-header">Method</th>
            <th width="" class="form-header">Reference</th>
            <th width="" class="form-header">Amount</th>
            <th width="" class="form-header">Date</th>
            <th width="100" class="form-header">Logged By</th>
            <th width="10" class="form-header"></th>
            <th width="10" class="form-header"></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $row = 0;
        $accessSleev = Utility_Functions::canUserAccess("/wholesale/payment");
        foreach ($this->entries as $entry) {    $row++;?>
            <tr class="row_<?php echo $row % 2; ?>">
                <td >
                    <a onclick="return confirm('Are you sure you want to delete this Payment?')" href="/wholesale/voidpayment/id/<?=$entry['payment_id']?>">
                        <img width="20" title="Delete Payment" src="/images/icons/famfam/delete.png" />
                    </a>
                </td>
                <td><?php echo $entry['inv_id']; ?></td>
                <td><?php echo $entry['cust_name']; ?></td>
                <td><?php echo $entry['cust_address'] . ',<br>' . $entry['cust_city'] . ',' . $entry['cust_state'] . ' ' . $entry['cust_zip']; ?></td>
                <td><?php echo $entry['payment_type']; ?></td>
                 <td><?php echo $entry['payment_contact']; ?></td>
                <td><?php echo $entry['payment_amount']; ?></td>
                <td><?php echo date('m/d/Y', strtotime($entry['payment_datetime'])); ?></td>
                <td><?php echo $entry['name']; ?></td>
                <td>
                    <?php if ($accessSleev) { ?>
                        <a href="/wholesale/payment/id/<?php echo $entry['payment_id']; ?>">
                            <img title="Edit Payment" src="/images/icons/famfam/pencil.png" />
                        </a>
                    <?php } ?>
                </td>
                <td>
                    <?php if ($accessSleev) { ?>
                        <a href="/wholesale/invoice/id/<?php echo $entry['inv_id']; ?>">
                            <img title="View Invoice" src="/images/icons/invoice.png" width="25" />
                        </a>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>