<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<div class="form_options">[ <a href="/wholesale/paymenttypes">Cancel</a> ]</div>

<form method="post" action="" class="show-loader">
    <?php //echo $this->form->cust_id; ?>
    <table id="form" width="600">
        <tr>
            <td colspan=2 class="top-header">Payment Methods Manager</td>
        </tr>
        <tr>
            <td class="form-header">Payment Method</td>
            <td class="form-field">
                <input type="text" name="PaymentType" id="PaymentType" required="required" value="" maxlength="255" class="form-element" size="30" >
            </td>
        </tr>
        <tr>
            <td colspan=2 class="form-submit">
                <input type="submit" name="submit" id="submit" value="Save" class="submit" />
            </td>
        </tr>
    </table>
</form>