<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo $this->meta_title; ?></title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="title"       content="<?php echo $this->meta_title; ?>" />
    <meta name="description" content="<?php echo $this->meta_description; ?>" />
    <meta name="keywords"    content="<?php echo $this->meta_keywords; ?>" />
    <meta name="googlebot"   content="<?php echo $this->meta_googlebots; ?>" />
    <meta name="robots"      content="<?php echo $this->meta_robots; ?>" />
    <meta http-equiv="cache-control" content="<?php echo $this->meta_cache; ?>" />
    <meta http-equiv="pragma"        content="<?php echo $this->meta_cache; ?>" />

    <link rel="icon"          href="<?php echo $this->links_icon; ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->links_shortcut; ?>" type="image/x-icon" />
    <link rel="image_src"     href="<?php echo $this->links_image; ?>" />

    <?php foreach ($this->js_docs as $js_doc): ?>
        <script type="text/javascript" src="<?php echo $js_doc; ?>"></script>
    <?php endforeach; ?>

    <?php foreach ($this->css_docs as $css_doc): ?>
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $css_doc; ?>" />
    <?php endforeach; ?>
</head>
<body>
    <div class="wrapper">
        <div class="header_wrapper">
            <div class="site_header">
                <?php
                echo $this->partial('/partials/header.phtml');
                ?>
            </div><!-- end site_header div -->
        </div><!-- end header_wrapper div -->

        <div id="navigation_anchor"></div>
        <div id="user_navigation">
            <div style="display:table;">
                <?php echo $this->partial('/partials/admin-navigation.phtml', array(
                        "favorites" => $this->favorites)); ?>
            </div>
        </div>
        
<!--        <div id="user_navigation">
            <div style="display:table;">
                <?php //echo $this->partial('/partials/menu.phtml',array( "menu"  => $menu )); ?>
            </div>
        </div>-->

        <div class="content_wrapper">
            <div class="site_content">
                <!-- PDF Files PopUp Window -->
                <div id="dialog" style="display: none;">
                    <div><iframe id="frame" width="100%" style="max-width: 860px;" height="800"></iframe></div>
                </div>
                <!-- PDF Files PopUp Window -->
                <?php echo $this->layout()->content; ?>
            </div><!-- end site_content div -->
        </div><!-- end content_wrapper div -->

        <div class="site_footer">
            <?php echo $this->partial('/partials/footer.phtml'); ?>
        </div><!-- end footer div -->
    </div><!-- end wrapper div -->
</body>
</html>