<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>BNY Wholesale :: <?php echo $this->title; ?></title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="title"       content="<?php echo $this->meta_title; ?>" />
    <meta name="description" content="<?php echo $this->meta_description; ?>" />
    <meta name="keywords"    content="<?php echo $this->meta_keywords; ?>" />
    <meta name="googlebot"   content="<?php echo $this->meta_googlebots; ?>" />
    <meta name="robots"      content="<?php echo $this->meta_robots; ?>" />
    <meta http-equiv="cache-control" content="<?php echo $this->meta_cache; ?>" />
    <meta http-equiv="pragma"        content="<?php echo $this->meta_cache; ?>" />

    <link rel="icon"          href="<?php echo $this->links_icon; ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->links_shortcut; ?>" type="image/x-icon" />
    <link rel="image_src"     href="<?php echo $this->links_image; ?>" />

    <?php foreach ($this->js_docs as $js_doc): ?>
        <script type="text/javascript" src="<?php echo $js_doc; ?>"></script>
    <?php endforeach; ?>

    <?php foreach ($this->css_docs as $css_doc): ?>
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $css_doc; ?>" />
    <?php endforeach; ?>
</head>
<body>
    <!-- The Modal -->
    <div id="myModal" class="modal" style="display: none;">
        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <p></p>
        </div>
    </div>
    <input name="image" type="file" id="upload" style="display: none;" class="hidden" onchange=""/>	
    <div class="wrapper">
        <div class="header_wrapper">
            <div class="site_header">
                <?php
                echo $this->partial('/partials/header.phtml');
                ?>
            </div><!-- end site_header div -->
        </div><!-- end header_wrapper div -->

        <div id="navigation_anchor"></div>
        <div id="user_navigation">
            <div style="display:table;">
                <?php echo $this->partial('/partials/admin-navigation.phtml', array(
                        "favorites" => $this->favorites)); ?>
            </div>
        </div>

<!--        <div id="user_navigation">
            <div style="display:table;">
                <?php //echo $this->partial('/partials/menu.phtml',array( "menu"  => $menu )); ?>
            </div>
        </div>-->
        
        <div class="content_wrapper">
            <div class="site_content">
                <!-- PDF Files PopUp Window -->
                <div id="dialog" style="display: none;">
                    <div><iframe id="frame" width="100%" style="max-width: 860px;" height="800"></iframe></div>
                </div>
                <!-- PDF Files PopUp Window -->
                <?php echo $this->layout()->content; ?>
            </div><!-- end site_content div -->
        </div><!-- end content_wrapper div -->

        <div class="site_footer">
            <?php echo $this->partial('/partials/footer.phtml'); ?>
        </div><!-- end footer div -->
    </div><!-- end wrapper div -->
    <!-- TinyMCE -->
    <?php if (!in_array(Utility_Functions::get_user_browser(), array("IE 8+", "IE 7-"))) { ?>
        <script type="text/javascript" src="/js/tinymce_new/js/tinymce/tinymce.min.js"></script>
        <script>
            tinymce.init({
                selector: "textarea",
                theme: "modern",
                width: '100%',
                height: '150px',
                paste_data_images: true,
                plugins: [
                    "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                    "searchreplace wordcount visualblocks visualchars code fullscreen",
                    "insertdatetime media nonbreaking save table contextmenu directionality",
                    "emoticons template paste textcolor colorpicker textpattern"
                ],
                toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link",
                toolbar2: "print preview media | forecolor backcolor emoticons",
                image_advtab: true,
                file_picker_callback: function(callback, value, meta) {
                    if (meta.filetype == 'image') {
                        $('#upload').trigger('click');
                        $('#upload').live('change', function() {
                            var file = this.files[0];
                            var reader = new FileReader();
                            reader.onload = function(e) {
                                callback(e.target.result, {
                                    alt: ''
                                });
                            };
                            reader.readAsDataURL(file);
                        });
                    }
                }
            });
        </script>
    <?php } else { ?>
        <script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
        <script type="text/javascript">
            tinyMCE.init({
                // General options
                mode : "textareas",
                theme : "advanced",
                plugins : "autolink,lists,pagebreak,style,layer,advhr,advimage,advlink,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist",
                // Theme options
                theme_advanced_buttons1 : "code,print,|,bold,italic,underline,|,justifyleft,justifycenter,justifyfull,|,bullist,numlist,|,indent,outdent,hr,|,sub,sup,charmap",
                theme_advanced_buttons2 : "",
                theme_advanced_buttons3 : "",
                theme_advanced_buttons4 : "",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "center",
                theme_advanced_resizing : false,
                width: '100%',
                height: '150px'
            });
        </script>
    <?php } ?>
    <!-- /TinyMCE -->
</body>
</html>