<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>			
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<!-- PAGE LIST -->
<div class="pages">
    <div class="table_top_options">
        <div class="options_section">[ <a href="/page/page">Create New Page</a> ]</div>
        <div class="clear"></div>
    </div><!-- end table_top_options div -->

    <table class="page_table" width="950">
        <thead>
            <tr>
                <th colspan=9 class="top-header">Page Manager</th>
            </tr>
            <tr>
                <th>#</th>
                <th>ID</th>
                <th>Page Name</th>
                <th>Path</th>
                <th>Page Group</th>
                <th>Active</th>
                <th>Dash</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            $row = 0;
            $accessPage     =   Utility_Functions::canUserAccess("/page/page");
            $accessActivate =   Utility_Functions::canUserAccess("/page/pageactivation");
            foreach ($this->pages as $page) { $row++; ?>
                <tr class="row_<?php echo $row % 2; ?>">
                    <td><?php echo $row; ?></td>
                    <td><?php echo $page['page_id']; ?></td>
                    <td><?php echo $page['page_name']; ?></td>
                    <td><?php echo $page['path']; ?></td>
                    <td><?php echo $page['page_group_name']; ?></td>
                    <td style="text-align: center;">
                        <?php if ($accessPage) { ?>
                            <a class="u_activate" val="<?php echo $page['page_active']; ?>" href="<?php echo $page['page_id']; ?>">
                            <?php if ($page['page_active'] == 0) { ?>
                                <img title="Activate" src="/images/icons/famfam/add.png" />
                            <?php } else if ($page['page_active'] == 1) { ?>
                                <img title="Deactivate" src="/images/icons/famfam/delete.png" />
                            <?php } ?>
                            </a>
                        <?php } ?>
                    </td>
                    <td><?php echo ( $page['show_in_dashboard'] == 1 ) ? "Yes" : "No"; ?></td>
                    <td style="text-align: center;">
                        <?php if ($accessPage) { ?>
                            <a href="/page/page/id/<?php echo $page['page_id']; ?>">
                                <img src="/images/icons/famfam/pencil.png" title="modify the selected page" />
                            </a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table><!-- end task_table -->
</div><!-- end pages div -->