<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
	<div class="bread_crumb">	
		<ul>
			<li><a href="/dashboard">Home</a></li>
            <li><a href="/page/usergroups">User Group List</a></li>		
			<li><?php echo $this->title; ?></li>
		</ul>
	</div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if( is_array($this->messages) && count($this->messages) > 0 ) { ?>
	<div id="messages">
		<ul>
		<?php foreach( $this->messages as $message ) { ?>
			<li><?php echo $message; ?></li>
		<?php } ?>
		</ul>
	</div><!-- end messages div -->
<?php } ?>

<div class="content_header"><?php echo $this->title; ?> [ group: <?php echo $this->permission_group->getPermission_group_title(); ?> ]</div>

<div id="usergroup_pagegroups">
	<ul class="page_groups">
    	<?php foreach( $this->pages as $page_group ) { ?>
        	<li>
            	<a href="#" class="expand_list" id="<?php echo $page_group['page_group_id']; ?>"
                	title="expand and view the contents of this page group">
                    <div class="pagegroup_title">
                        <div class="left_end"></div>
                        <div class="label"><?php echo $page_group['page_group_name']; ?></div>
                        <div class="right_end"></div>
                        <div class="clear"></div>
                    </div>
                </a>
                <ul class="pages" id="pages_<?php echo $page_group['page_group_id']; ?>">
                	<li>
                    	<table class="inner_page_table">
                        	<tbody>
                            	<?php 
                                $i=0; 
                                if(Utility_Functions::canUserAccess("readOnly")) $read_only=true;
                                else $read_only=false;
                                ?>
                                <?php foreach( $page_group['pages'] as $page ) { ?>
                                    <tr class="row_<?php echo $i%2; ?>" id="<?php echo $page['page_id']; ?>">
                                        <td width="230"><?php echo $page['page_name']; ?></td>
                                        <td><?php echo $page['path']; ?></td>
                                        <td width="143">
                                            <?php if( $read_only ) { ?>
                                            	<?php if( isset($this->pg_pages[$page['page_id']]['page_name']) ) { ?>
                                                	<div class="yes-on" id="yes_<?php echo $page['page_id']; ?>">Yes</div>
                                                	<div class="no-off" id="no_<?php echo $page['page_id']; ?>">No</div>
                                                    <div class="clear"></div>
                                                <?php } else { ?>
                                               		<div class="yes-off" id="yes_<?php echo $page['page_id']; ?>">Yes</div>
                                                	<div class="no-on" id="no_<?php echo $page['page_id']; ?>">No</div>
                                                	<div class="clear"></div>
                                                <?php } ?>
                                        	<?php } else if( isset($this->pg_pages[$page['page_id']]['page_name']) ) { ?>
                                                <a class="change" href="/page/usergrouppageassignment/group/<?php echo $this->permission_group->getPermission_group_id(); ?>/page/<?php echo $page['page_id']; ?>">
                                                	<div class="yes-on" id="yes_<?php echo $page['page_id']; ?>">Yes</div>
                                                </a>
                                                <a class="change" href="/page/usergrouppageremoval/group/<?php echo $this->permission_group->getPermission_group_id(); ?>/page/<?php echo $page['page_id']; ?>">
                                                	<div class="no-off" id="no_<?php echo $page['page_id']; ?>">No</div>
                                                </a>
                                                <div class="clear"></div>
                                            <?php } else { ?>
                                                <a class="change" href="/page/usergrouppageassignment/group/<?php echo $this->permission_group->getPermission_group_id(); ?>/page/<?php echo $page['page_id']; ?>">
                                                	<div class="yes-off" id="yes_<?php echo $page['page_id']; ?>">Yes</div>
                                                </a>
                                                <a class="change" href="/page/usergrouppageremoval/group/<?php echo $this->permission_group->getPermission_group_id(); ?>/page/<?php echo $page['page_id']; ?>">
                                                	<div class="no-on" id="no_<?php echo $page['page_id']; ?>">No</div>
                                                </a>
                                                <div class="clear"></div>
                                            <?php } ?>
                                        </td>
                                    </tr>
                                    <?php ++$i; ?>
                                <?php } ?>
                            </tbody>
                    	</table>
                	</li>
                </ul>
            </li>
    	<?php } ?>
	</ul>
</div><!-- end usergroup_assignments div -->