<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>			
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<!-- USER GROUP LIST -->
<div class="permission_groups">
    <?php if (Utility_Functions::canUserAccess("/page/usergroup")) { ?>
        <div class="form_options">
            [ <a href="/page/usergroup">Create New User Group</a> ]
        </div>
    <?php } ?>            
    <table class="page_table" width="840">
        <thead>
            <tr>
                <th class="top-header" colspan="3">User Group Manager</th>
            </tr>
            <tr>
                <th width="25" class="form-header">ID</th>
                <th width="450" class="form-header">User Group Name</th>
                <th width="100" class="form-header">Options</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $read_only      = Utility_Functions::canUserAccess("readOnly");
            $usergroup      = Utility_Functions::canUserAccess("/page/usergroup");
            $usergroupusers = Utility_Functions::canUserAccess("/page/usergroupusers");
            $usergrouppages = Utility_Functions::canUserAccess("/page/usergrouppages");
            $newusergrouppages = Utility_Functions::canUserAccess("/page/newusergrouppages");
            $row = 0;
            foreach ($this->permission_groups as $permission_group) { ?>
                <tr class="row_<?php echo $row % 2; ?>" id="<?php echo $permission_group['permission_group_id']; ?>">
                    <td><?php echo $permission_group['permission_group_id']; ?></td>
                    <td><?php echo $permission_group['permission_group_title']; ?></td>
                    <td style="text-align: center;">
                        <?php if ($usergroup && !$read_only) { ?>
                            <a href="/page/usergroup/id/<?php echo $permission_group['permission_group_id']; ?>">
                                <img src="/images/icons/famfam/pencil.png" title="modify the selected permission group" />
                            </a>
                        <?php } ?>
                        <?php if ($usergroupusers) { ?>
                            <a href="/page/usergroupusers/id/<?php echo $permission_group['permission_group_id']; ?>">
                                <img src="/images/icons/famfam/group_add.png" title="add users to this group" />
                            </a>
                        <?php } ?>
                        <?php if ($usergrouppages) { ?>
                            <a href="/page/usergrouppages/id/<?php echo $permission_group['permission_group_id']; ?>">
                                <img src="/images/icons/famfam/application_add.png" title="add page permissions to this group" />
                            </a>
                        <?php } ?>
                        <?php if ($newusergrouppages) { ?>
                            <a href="/page/newusergrouppages/id/<?php echo $permission_group['permission_group_id']; ?>">
                                <img src="/images/icons/famfam/application_side_expand.png" title="add page permissions to this group" />
                            </a>
                        <?php } ?>
                    </td>
                </tr>
                <?php ++$row; ?>
            <?php } ?>
        </tbody>
    </table><!-- end task_table -->
</div><!-- end page div -->