
<div id="message"></div>
<h4 class="display-4"><?=$this->category['cat_name']?></h4>
<div class="row mt-2 pb-3">
    <?php
    foreach ($this->rows as $row) {
        if(file_exists(Zend_Registry::get("target_path")."/uploads/products/".$row['prod_image']) && !empty($row['prod_image'])){
            $image = "/uploads/products/".$row['prod_image'];
        }else{
            $image = "/uploads/products/empty_img.png"; 
        }
        ?>
        <div class="col-sm-6 col-md-4 col-lg-3 mb-2">
            <div class="card-deck">
                <div class="card p-2 border-secondary mb-2">
                    <a href="<?= $image ?>"  class="example-image-link" data-lightbox="products"  alt="<?= $row['prod_desc'] ?>" title="<?= $row['prod_desc'] ?>">
                        <img src="<?= $image ?>" class="card-img-top example-image" alt="<?= $row['prod_desc'] ?>" title="<?= $row['prod_desc'] ?>" height="250">
                    </a>
                    <div class="card-body p-1" style="height: 70px; overflow: hidden;">
                        <h5 class="card-title text-center text-info" style="font-size: 1.15rem">
                            <a href="/cart/product/id/<?= $row['prod_id'] ?>"><?= $row['prod_desc'] ?></a>
                        </h5>
                    </div>
                    <?php if($this->user_id){ ?>
                    <div class="card-body p-1" style="height: 30px;">
                        <h5 class="card-text text-center text-danger"><i class="fas fa-dollar-sign"></i>&nbsp;&nbsp;<?= number_format($row['prod_sale'], 2) ?></h5>
                    </div>
                    <div class="card-footer p-1">
                        <form action="" class="form-submit">
                            <div class="row p-2">
                                <div class="col-md-6 py-1 pl-2">
                                    <b>Quantity</b>
                                </div>
                                <div class="col-md-6">
                                    <input type="number" class="form-control pqty" value="<?= $row['product_qty'] ?>">
                                </div>
                            </div>
                            <input type="hidden" class="pid" value="<?= $row['prod_id'] ?>">
                            <input type="hidden" class="pname" value="<?= $row['prod_desc'] ?>">
                            <input type="hidden" class="pprice" value="<?= $row['prod_sale'] ?>">
                            <input type="hidden" class="pimage" value="<?= $row['prod_image'] ?>">
                            <input type="hidden" class="pcode" value="<?= $row['prod_code'] ?>">
                            <button class="btn btn-info btn-block addItemBtn"><i class="fas fa-cart-plus"></i>&nbsp;&nbsp;Add to cart</button>
                        </form>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    <?php } ?>
</div>
<!-- Displaying Products End -->
<script type="text/javascript">
$(document).on("click", '[data-toggle="lightbox"]', function(event) {
  event.preventDefault();
  $(this).ekkoLightbox();
});
    $(document).ready(function () {

        // Send product details in the server
        $(".addItemBtn").click(function (e) {
            e.preventDefault();
            var $form = $(this).closest(".form-submit");
            var pid = $form.find(".pid").val();
            var pname = $form.find(".pname").val();
            var pprice = $form.find(".pprice").val();
            var pimage = $form.find(".pimage").val();
            var pcode = $form.find(".pcode").val();
            var pqty = $form.find(".pqty").val();
            $.ajax({
                url: '/cart/action',
                method: 'post',
                data: {
                    pid: pid,
                    pname: pname,
                    pprice: pprice,
                    pqty: pqty,
                    pimage: pimage,
                    pcode: pcode
                },
                success: function (response) {
                    $("#message").html(response);
                    window.scrollTo(0, 0);
                    load_cart_item_number();
                }
            });
        });

        // Load total no.of items added in the cart and display in the navbar
        load_cart_item_number();

        function load_cart_item_number() {
            $.ajax({
                url: '/cart/action',
                method: 'get',
                data: {
                    cartItem: "cart_item"
                },
                success: function (response) {
                    $("#cart-item").html(response);
                }
            });
        }
    });
</script>